server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://thuongmaidientu1-quyenthaoxyz123-6026.k.aivencloud.com:25291/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    secret: "change-this-secret-key-to-at-least-32-characters"

app:
  default-admin-email: admin@ecommerce.com
  default-admin-password: Admin@123
